import _Layout from "./Layout";
import _AppBar from "./AppBar";
import _Sidebar from "./Sidebar";
import _Tabs from "./Tabs";
import _QuestionForm from "./QuestionForm";
import _QuestionResult from "./QuestionResult";
import _ProgressBar from "./ProgressBar";
import _NewQuestionForm from "./NewQuestionForm";
import _Profile from "./Profile";
import _Page from "./Page";
import _LoginForm from "./LoginForm";

export const Layout = _Layout;
export const AppBar = _AppBar;
export const Sidebar = _Sidebar;
export const Tabs = _Tabs;
export const QuestionForm = _QuestionForm;
export const QuestionResult = _QuestionResult;
export const ProgressBar = _ProgressBar;
export const NewQuestionForm = _NewQuestionForm;
export const Profile = _Profile;
export const Page = _Page;
export const LoginForm = _LoginForm;
