const User = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
};

const Users = {
  USERS_REQUEST: "USERS_REQUEST",
  USERS_SUCCESS: "USERS_SUCCESS",
  USERS_FAILED: "USERS_FAILED",
};

const Questions = {
  QUESTIONS_REQUEST: "QUESTIONS_REQUEST",
  QUESTIONS_SUCCESS: "QUESTIONS_SUCCESS",
  QUESTIONS_FAILED: "QUESTIONS_FAILED",
};

export default { User, Users, Questions };
